### PR TITLE
Add macOS instructions

### PR DESCRIPTION
**Pull request by chamindujs**
**Added macOS instructions for navigating and editing files.**

There were only Windows and Linux CLI commands. I added macOS commands too. Yes, it is just like Linux commands, but some are different.

### CODE REVIEW

**Review by garg3133 — CHANGES_REQUESTED** [review]

**Comment by chamindujs** [comment]
I think I resolved it all.

**Comment by garg3133** [comment]
Yes, the changes looks good now.

Merging the PR. Thanks @chamindujs

**Comment by chamindujs** [comment]
@garg3133  Hey, can you add **"hacktoberfest-accepted"** label to my PR? So my contribution would count towards [Hacktoberfest](https://hacktoberfest.digitalocean.com/).

image

Please be kind enough to consider my message.

**Comment by garg3133** [comment]
Yeah sure, NP :)

**Pull request merged**
