### PR TITLE
Github Id guide and badges for actions

### PR DESCRIPTION
**Pull request by avats-dev**
Also added some references in where to go after this. :tada:

### CODE REVIEW

**Comment by avats-dev** [comment]
#30

**Comment by garg3133** [comment]
@avats-dev Can you also please update the links in `Make necessary changes` section from `Commit your changes` to `Before you commit` section.

**Comment by avats-dev** [comment]
> @avats-dev Can you also please update the links in `Make necessary changes` section from `Commit your changes` to `Before you commit` section. The link appears 3 times in that section.

@garg3133 Done :rocket:

**Comment by garg3133** [comment]
Looks good, merged! Thanks @avats-dev

**Pull request merged**
